

Nội dung
1. Các lệnh cơ bản trong numpy.
2. Các lệnh cơ bản trong machine learning. (bổ sung dần)

source: https://www.tutorialspoint.com/numpy/index.htm

In [1]:
import numpy as np

1 Các lệnh cơ bản trong numpy

Khởi tạo ma trận, kích thước ma trận

In [2]:
# vecto
x = np.array([1, 2, 3, 4])
print(x)
print(x[2]) # lấy ra phần tử thứ 3, phần tử đầu tiên index =0
print(x[-1]) # lấy ra phần tử cuối cùng
print(x.shape)
# Matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)
m ,n = A.shape # m số hàng = A.shape[0] , n là số cột = A.shape[1]
print(A.shape)
print(A[1]) # lấy ra hàng (block) thứ 2.


[1 2 3 4]
3
4
(4,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[4 5 6]


In [3]:
# matrix zeros nxn
A = np.zeros((2,2))
# matrix ones nxn
B = np.ones((3,3))
# matrix đơn vị
C = np.eye(4)
print(A)
print(B)
print(C)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Các phép toán cơ bản trên ma trận

In [4]:
# các phép toán trên ma trận
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
# cộng hai ma trận có cùng kích thước
C = np.add(A,B) # or C =  A + B
print(C)
# hiệu hai ma trận có cùng kích thước
D = np.subtract(A,B) # or D = A - B
print(D)
# tích hai ma trận A = (m; n) và B =(n; p)  số cột ma trận VT = số hàng ma trận vế phải
E = np.dot(A, B) # or E = A.dot(B)
print(E)
# tích từng phần tử của ma trận A với từng phần tử của ma trận B
F = np.multiply(A, B) # or F = A * B
print(F)
# tìm ma trận nghịch đảo của ma trận vuông A
G = np.linalg.inv(A)
print(G)
print(G.dot(A)) # kết quả là ma trận đơn vị
# chuyển vị của ma trận
T = A.T
print(T)

[[ 3  6  9]
 [12 15 18]
 [21 24 28]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -8]]
[[ 60  72  84]
 [132 162 192]
 [218 268 318]]
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 180]]
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 1.33226763e-15  1.00000000e+00  8.88178420e-16]
 [-7.77156117e-16  0.00000000e+00  1.00000000e+00]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]


2 Các lệnh cơ bản trong machine learning



In [5]:
# vecto 
x = np.array([1,2,3])
print(x)
# matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A.dot(x))

[1 2 3]
[14 32 50]


In [6]:
# reshape ma trận A
C = A.reshape(1,9) # đưa ma trận A về ma trận có kích thước (m,n)
print(C)
D = A.reshape(9,1)
print(D)

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
# thêm số vào từng hàng cho ma trận A
one = np.ones((A.shape[0], 1))
print(one)
A_bar = np.concatenate((one, A), axis =1)
print(A_bar)

[[1.]
 [1.]
 [1.]]
[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


In [8]:
# sắp xếp một vecto, một ma trận
x = np.array ([11, 5, 4, 3, 8])
print(np.sort(x))
A = np.array([[9, 5, 3],[4, 1, 2]])
print(np.sort(A))

[ 3  4  5  8 11]
[[3 5 9]
 [1 2 4]]


In [9]:
# trả về vecto giá trị lớn nhất, nhỏ nhất trong mỗi hàng ma trận
c = np.min(A, axis = 1)
print(c)
d = np.max(A, axis = 1)
print(d)


[3 1]
[9 4]


In [10]:
# trả về vecto các phần tử giống nhau đã sắp xếp
x = np.array([2, 1, 4, 6, 8, 2, 4, 3,4])
e = np.unique(x)
print(e)

[1 2 3 4 6 8]


In [11]:
# tính tổng các phần tử trong một hàng của ma trận A
print(A)
# tổng tất cả
E = np.sum(A)
print(E)
# tổng từng cột
F = np.sum(A, axis = 0)
print(F)
# tổng từng hàng
G = np.sum(A, axis = 1)
print(G)

[[9 5 3]
 [4 1 2]]
24
[13  6  5]
[17  7]
