# Xây dựng neural netwok xử lý bài toán XOR bằng thư viện keras

In [4]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [2]:
x_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([[0], [1], [0], [1]])

Thiếp lập model

In [3]:
model = Sequential()
num_neurons = 10
model.add(Dense(num_neurons, input_dim = 2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                30        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


`summary()`: thống kê mô hình.

`Sequential()`: khởi tạo một neurol tuần tự.

`add Dense()` : thêm lớp fully connected layer.

`add Activation()`: thêm hàm kích hoạt.


Mô hình trên thiết lập mạng gồm 2 layer :
+ 1 lớp đầu vào với hai tham số (không tính là layer của mạng).
+ 1 lớp ẩn với 10 tham số, hàm kích hoạt là hàm `tank`. (dense1)
+ 1 lớp output với hàm kích hoạt là `sigmoid`. (desen2)


Nếu đầu ra nhỏ hơn 0.5 sẽ trả về 0 và lớn hơn 0.5 sẽ trả về 1. Đây là bài toán phân lớp nhị phân.
+ số tham số đầu vào của dense_1 là :30, bao gồm 3 node input (2 + bias), lớp dense_1 có 10 node.
+ số tham số ở cặp (dense_1, dense_2) là 11 (10 node + bias)


Tiếp theo chúng ta gọi hàm loss là hàm cross_entropy (tốt cho phân lớp nhị phân), sử dụng `SGD` để tối ưu, gọi là metric là accuracy để có thể hiện thị kết quả đánh giá của mô hình qua từng epcho khi train.

In [5]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Trước khi train, kết quả x_train

In [6]:
model.predict(x_train)

array([[0.5       ],
       [0.30973023],
       [0.31064898],
       [0.18140414]], dtype=float32)

In [7]:
model.fit(x_train, y_train, epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 104ms/step - loss: 0.9861 - accuracy: 0.5000
Epoch 2/200
4/4 [==============================] - 0s 498us/step - loss: 0.9382 - accuracy: 0.2500
Epoch 3/200
4/4 [==============================] - 0s 748us/step - loss: 0.8959 - accuracy: 0.2500
Epoch 4/200
4/4 [==============================] - 0s 499us/step - loss: 0.8583 - accuracy: 0.2500
Epoch 5/200
4/4 [==============================] - 0s 498us/step - loss: 0.8250 - accuracy: 0.2500
Epoch 6/200
4/4 [==============================] - 0s 250us/step - loss: 0.7953 - accuracy: 0.2500
Epoch 7/200
4/4 [==============================] - 0s 749us/step - loss: 0.7687 - accuracy: 0.2500
Epoch 8/200
4/4 [==============================] - 0s 249us/step - loss: 0.7448 - accuracy: 0.5000
Epoch 9/200
4/4 [==============================] - 0s 499us/step - loss: 0.7233 - accuracy: 0.5000
Epoch 10/200
4/4 [==============================] - 0s 499us/step - loss: 0.7036 - accuracy: 0.5000
Epoch 11/

Epoch 84/200
4/4 [==============================] - 0s 748us/step - loss: 0.1590 - accuracy: 1.0000
Epoch 85/200
4/4 [==============================] - 0s 249us/step - loss: 0.1561 - accuracy: 1.0000
Epoch 86/200
4/4 [==============================] - 0s 249us/step - loss: 0.1533 - accuracy: 1.0000
Epoch 87/200
4/4 [==============================] - 0s 249us/step - loss: 0.1505 - accuracy: 1.0000
Epoch 88/200
4/4 [==============================] - 0s 249us/step - loss: 0.1478 - accuracy: 1.0000
Epoch 89/200
4/4 [==============================] - 0s 243us/step - loss: 0.1451 - accuracy: 1.0000
Epoch 90/200
4/4 [==============================] - 0s 748us/step - loss: 0.1425 - accuracy: 1.0000
Epoch 91/200
4/4 [==============================] - 0s 499us/step - loss: 0.1400 - accuracy: 1.0000
Epoch 92/200
4/4 [==============================] - 0s 997us/step - loss: 0.1376 - accuracy: 1.0000
Epoch 93/200
4/4 [==============================] - 0s 249us/step - loss: 0.1352 - accuracy: 1.0000


Epoch 166/200
4/4 [==============================] - 0s 500us/step - loss: 0.0512 - accuracy: 1.0000
Epoch 167/200
4/4 [==============================] - 0s 250us/step - loss: 0.0507 - accuracy: 1.0000
Epoch 168/200
4/4 [==============================] - 0s 249us/step - loss: 0.0502 - accuracy: 1.0000
Epoch 169/200
4/4 [==============================] - 0s 499us/step - loss: 0.0497 - accuracy: 1.0000
Epoch 170/200
4/4 [==============================] - 0s 499us/step - loss: 0.0492 - accuracy: 1.0000
Epoch 171/200
4/4 [==============================] - 0s 249us/step - loss: 0.0488 - accuracy: 1.0000
Epoch 172/200
4/4 [==============================] - 0s 249us/step - loss: 0.0483 - accuracy: 1.0000
Epoch 173/200
4/4 [==============================] - 0s 250us/step - loss: 0.0478 - accuracy: 1.0000
Epoch 174/200
4/4 [==============================] - 0s 250us/step - loss: 0.0474 - accuracy: 1.0000
Epoch 175/200
4/4 [==============================] - 0s 250us/step - loss: 0.0469 - accurac

Thực hiện dự đoán

In [8]:
model.predict(x_train)

array([[0.05110408],
       [0.97512686],
       [0.03413084],
       [0.9631553 ]], dtype=float32)

In [9]:
model.predict_classes(x_train)

array([[0],
       [1],
       [0],
       [1]])

Lưu model

In [10]:
import h5py
# Xuất cấu trúc của mạng đến một JSON blob để sử dụng sau 
model_structure = model.to_json()
with open("basic_mode.json", "w") as json_file:
    json_file.write(model_structure)
# Các trọng số được đào tạo phải được lưu riêng biệt. 
# Lưu trọng số để load lại chúng chúng sau này.
model.save_weights("basic_weights.h5")