# Feature engineering
Nội dung
1. Giới thiệu về feature vertor.
2. Mô hình chung cho bài toán Machine Learning.
3. Một số ví dụ về Featrue Engineering.

Tài liệu:

https://machinelearningcoban.com/general/2017/02/06/featureengineering/

 1. Giới thiệu về feature vertor.
 
Mỗi điểm dữ liệu trong các bài toán Machine Learning thường được biểu diễn bằng một vector, được gọi là vector đặc trưng (feature vector). Trong một bài toán, để tính toán trong mô hình, các feature vector của tất cả các điểm thường có kích thước như nhau. Toàn bộ các vector được lưu thành một ma trận. Ở dữ liệu thô, kích thước của các điểm thường khác nhau.

VD: Trong computer vision, các bức ảnh thường là các ma trận hoặc các tensor có kích thước khác nhau. Trong natural language processing độ dài các văn bản thường là khác nhau.

Chúng ta cần tìm cách loại bỏ những điểm dữ liệu nhiễu, để đưa dữ liệu thô về cùng một chuẩn. Qúa trình này gọi là <b> trích chọn đặc trưng (feature engineering).

2. Mô hình chung cho bài toán Machine Learning. 

(Xem tài liệu tham khảo)


3. Một số ví dụ về Featrue Engineering

Đối với bài toán xử lý ảnh, mỗi bức ảnh có độ dài m.n pixel, cách đơn giản nhất là kéo dài ma trận thành các pixel thành một vecto có m.n phần tử, kỹ thuật này còn gọi là vecto hóa (vectorization). Các điểm dữ liệu có số đặc trung khác nhau (do kích thước khác nhau) và số lượng đặc trưng cực lớn, ta cần chọn ra một số đặc trưng nhỏ hơn để phù hợp với bài toán. Với dữ liệu có số chiều rất lớn, phương pháp được dùng là làm giảm chiều dữ liệu, để giảm bộ nhớ và khối lượng tính toán. (Chi tiết CNN và xử lý ảnh)

# Bag of words

Bag of word -BoW là kĩ thuật phổ biến trong xử lý văn bản.



Cho hai văn bản sau:

(1) "John likes to watch movies. Marry likes movies too."

(2) "John also likes to watch football games."

Danh sách từ điển dựa trên hai văn bản là:

$["John", "likes", "to", "watch","movies", "also", football", "games", "Mary", "too"]$

Với hai văn bản trên ta sẽ có được hai vector đặc trưng có số chiều bằng số chiều của từ điển, mỗi phần tử đại diện cho số từ xuất hiện trong văn bản đó:

(1) $[1,2,1,1,2,0,0,0,1,1]$

(2)$[1,1,1,1,0,1,1,1,0,0]$

In [55]:
import numpy as np

str1 = "John likes to watch movies  Marry likes movies too"
str1_new    = list(str1.split()) #covert string to list
str2 = "John also likes to watch football games "
str2_new = list(str2.split())    #covert string to list
dictionary = np.unique(np.array(str1_new + str2_new))
print("Danh sách từ điển:",dictionary)
feature_str1 = np.zeros(dictionary.shape[0])
str1_new = np.array(str1_new)
str2_new = np.array(str2_new)
print("Đoạn văn 1:",str1_new)
print("Đoạn văn 2:",str2_new)
for i in range(dictionary.shape[0]):
    dem = 0
    for j in range(str1_new.shape[0]):
        if str1_new[j] == dictionary[i]:  
            dem = dem + 1
        feature_str1[i] = dem
print(feature_str1 )
         

Danh sách từ điển: ['John' 'Marry' 'also' 'football' 'games' 'likes' 'movies' 'to' 'too'
 'watch']
Đoạn văn 1: ['John' 'likes' 'to' 'watch' 'movies' 'Marry' 'likes' 'movies' 'too']
Đoạn văn 2: ['John' 'also' 'likes' 'to' 'watch' 'football' 'games']
[1. 1. 0. 0. 0. 2. 2. 1. 1. 1.]


In [50]:
def feature_vector(str,dic):
    feature_str = np.zeros(dic.shape[0])
    for i in range(dic.shape[0]):
        item = 0
        for j in range(str.shape[0]):
            if str[j] == dic[i]:
                item = item +1
            feature_str[i] = item
    return feature_str

In [51]:
print(feature_vector(str1_new,dictionary))

[1. 1. 0. 0. 0. 2. 2. 1. 1. 1.]


In [54]:
print(feature_vector(str2_new,dictionary))

[1. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
